apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: webpushvariants.push.aerogear.org
spec:
  group: push.aerogear.org
  names:
    kind: WebPushVariant
    listKind: WebPushVariantList
    plural: webpushvariants
    singular: webpushvariant
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            alias:
              description: Alias is sent to a web push push service and must be either
                a url or mailto link.  The purpose is to provide a way for the push
                service to identify the sender of the message.
              type: string
            description:
              description: Description is a human friendly description for the variant.
              type: string
            privateKey:
              description: PrivateKey is the private part of a VAPID keypair. It is
                used to sign messages and identify them as being from this server
                by the client.
              type: string
            publicKey:
              description: PublicKey is the public part of a VAPID keypair. This will
                be transmitted to the user in the mobile-services.json file and the
                client uses it to verify messages were send by this server.
              type: string
            pushApplicationId:
              description: PushApplicationId is the Id of the Application that this
                Variant corresponds to in the UnifiedPush Server admin UI.
              type: string
          required:
          - privateKey
          - publicKey
          - alias
          - pushApplicationId
          type: object
        status:
          properties:
            message:
              type: string
            ready:
              type: boolean
            secret:
              type: string
            variantId:
              type: string
          required:
          - ready
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
